LARGE_MODEL = 'models/yolov8l.pt'
NANO_MODEL = 'models/yolov8n.pt'
TRACKING_BUFFER = 200
USE_GPU = True
BOX_THICKNESS = 4
YOLO_BLOCKLIST = (0, 25, 63, 73, 64)

DEFAULT_SCREEN_SIZE = (1920, 1080)
BACKGROUND_COLOR = 'black'
TEXT_COLOR = 'black'
FONT_SIZE = 32

SERVER_PORT = 6969
HOST = 'http://localhost'
